import SettingsRow from "../../components/ui/SettingsRow";
import SaveButton from "../../components/ui/SaveButton";

export default function SignatoryTab({ readOnly }) {
  return (
    <div className="settings-section">
      <div className="settings-section-title">Document Signatory Configuration</div>
      <div className="info-box" style={{ marginBottom: 14 }}>
        These names appear on all printed certificates, blotters, and official documents generated by the system.
      </div>
      <SettingsRow label="Certifying Official" sub="Signs all barangay certificates" defaultValue="HON. RICARDO M. SANTOS" readOnly={readOnly} />
      <SettingsRow label="Position Title" sub="Title under certifying official" defaultValue="Punong Barangay" readOnly={readOnly} />
      <SettingsRow label="Prepared By" sub="For certificates and documents" defaultValue="LEONORA T. DELA CRUZ" readOnly={readOnly} />
      <SettingsRow label="Prepared By Position" sub="Title under preparer's name" defaultValue="Barangay Secretary" readOnly={readOnly} />
      <SettingsRow label="OR Received By" sub="Default name on official receipts" defaultValue="ALMA T. CRUZ" readOnly={readOnly} />
      <SettingsRow label="OR Received By Position" sub="Title on official receipts" defaultValue="Accounting Clerk" readOnly={readOnly} />
      <SettingsRow label="Dry Seal Label" sub="Text near seal placeholder" defaultValue="Barangay Caroyroyan Official Seal" readOnly={readOnly} />
      <div style={{ marginTop: 14 }}><SaveButton readOnly={readOnly} /></div>
    </div>
  );
}
