import Modal from "../ui/Modal";
import { useModal } from "../../context/ModalContext";

export default function RecordPaymentModal() {
  const { closeModal, openModal } = useModal();

  return (
    <Modal title="Record New Cash Payment" onClose={closeModal} size="lg" footer={
      <>
        <button className="btn btn-outline" onClick={closeModal}>Cancel</button>
        <button className="btn btn-success" onClick={() => openModal("orPreview")}>
          Record & Issue Official Receipt
        </button>
      </>
    }>
      <div className="form-grid grid-col-2">
        <div><label className="f-label">OR Number</label><input className="f-input" placeholder="Auto-generated by system" /></div>
        <div><label className="f-label">Date</label><input className="f-input" type="date" /></div>
        <div className="form-col-2">
          <label className="f-label">Payer Full Name</label>
          <input className="f-input" placeholder="Name of payer" />
        </div>
        <div>
          <label className="f-label">Certificate Type</label>
          <select className="f-input">
            <option>Barangay Clearance</option><option>Certificate of Residency</option>
            <option>Certificate of Indigency</option><option>Business Clearance</option>
          </select>
        </div>
        <div>
          <label className="f-label">Certificate Reference No.</label>
          <input className="f-input" placeholder="e.g. CR-2026-XXXX" />
        </div>
        <div><label className="f-label">Amount Paid (₱)</label><input className="f-input" type="number" placeholder="0.00" /></div>
        <div>
          <label className="f-label">Mode of Payment</label>
          <select className="f-input"><option>Cash</option></select>
        </div>
        <div className="form-col-2">
          <label className="f-label">Received By</label>
          <input className="f-input" placeholder="Accounting Clerk name" />
        </div>
        <div className="form-col-2">
          <div className="warn-box">
            <strong>⚠ CASH PAYMENTS ONLY</strong> — No online payment gateway integrated. All
            records forwarded to Treasurer for validation.
          </div>
        </div>
      </div>
    </Modal>
  );
}
